import localFont from "next/font/local";
import { MarketItem } from "./EngraveType";
import EngraveService from "@/service/EngraveService";

export type PageProps = {
  children?: (JSX.Element | string)[] | (JSX.Element | string);
  className?: string;
};

export type ModalProps = {
  children?: (JSX.Element | string)[] | (JSX.Element | string);
  className?: string;
  isOpen?: boolean;
};

export const roboto = localFont({
  src: [
    {
      path: "../public/fonts/Roboto/Roboto-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Roboto/Roboto-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Roboto/Roboto-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
});

export const nanumNeo = localFont({
  src: [
    {
      path: "../public/fonts/NanumSquareNeo/NanumSquareNeo-aLt.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/NanumSquareNeo/NanumSquareNeo-bRg.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/NanumSquareNeo/NanumSquareNeo-cBd.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/NanumSquareNeo/NanumSquareNeo-dEb.woff",
      weight: "800",
      style: "normal",
    },
  ],
});

export const gradeClassMap: { [key: string]: string } = {
  일반: "normalBackground",
  고급: "uncommonBackground",
  희귀: "rareBackground",
  영웅: "epicBackground",
  전설: "legendaryBackground",
  유물: "relicBackground",
  고대: "ancientBackground",
  에스더: "siderealBackground",
};

export const gradeTextColorMap: { [key: string]: string } = {
  일반: "commonColor",
  고급: "uncommonColor",
  희귀: "rareColor",
  영웅: "epicColor",
  전설: "legendaryColor",
  유물: "relicColor",
  고대: "ancientColor",
  에스더: "siderealColor",
};

export const classImageMap: { [key: string]: string } = {
  호크아이: "class_1.png",
  소서리스: "class_2.png",
  건슬링어: "class_3.png",
  창술사: "class_4.png",
  서머너: "class_5.png",
  기상술사: "class_6.png",
  블레이드: "class_7.png",
  스트라이커: "class_8.png",
  슬레이어: "class_9.png",
  버서커: "class_10.png",
  워로드: "class_11.png",
  리퍼: "class_12.png",
  아르카나: "class_13.png",
  디스트로이어: "class_14.png",
  홀리나이트: "class_15.png",
  데모닉: "class_16.png",
  블래스터: "class_17.png",
  배틀마스터: "class_18.png",
  기공사: "class_19.png",
  도화가: "class_20.png",
  인파이터: "class_21.png",
  스카우터: "class_22.png",
  데빌헌터: "class_23.png",
  바드: "class_24.png",
  "전사(남)": "class_25.png",
  "전사(여)": "class_26.png",
  "무도가(남)": "class_27.png",
  "무도가(여)": "class_28.png",
  "헌터(남)": "class_29.png",
  "헌터(여)": "class_30.png",
  마법사: "class_31.png",
  암살자: "class_32.png",
  스페셜리스트: "class_33.png",
};

export const CATEGORY_CODE: { [key: string | number]: number } = {
  목걸이: 200010,
  0: 200010,
  귀걸이: 200020,
  1: 200020,
  반지: 200030,
  2: 200030,
  팔찌: 200040,
  "어빌리티 스톤": 30000,
  아뮬렛: 170300,
  보석: 210000,
  각인서: 40000,
};

export const ETC_OPTION_CODE: { [key: string]: number | null } = {
  ANY: null,
  // 전투 특성
  "전투 특성": 2,
  치명: 15,
  특화: 16,
  제압: 17,
  신속: 18,
  인내: 19,
  숙련: 20,
  // 각인 효과
  "각인 효과": 3,
  원한: 118,
  "굳은 의지": 123,
  "실드 관통": 237,
  강령술: 243,
  "저주받은 인형": 247,
  각성: 255,
  "안정된 상태": 111,
  "위기 모면": 140,
  "달인의 저력": 238,
  "중갑 착용": 240,
  "강화 방패": 242,
  "부러진 뼈": 245,
  승부사: 248,
  "기습의 대가": 249,
  "마나의 흐름": 251,
  돌격대장: 254,
  "약자 무시": 107,
  "정기 흡수": 109,
  "에테르 포식자": 110,
  "슈퍼 차지": 121,
  구슬동자: 134,
  "예리한 둔기": 141,
  불굴: 235,
  "여신의 가호": 239,
  선수필승: 244,
  "급소 타격": 142,
  "분쇄의 주먹": 236,
  "폭발물 전문가": 241,
  "번개의 분노": 246,
  바리케이드: 253,
  "마나 효율 증가": 168,
  "최대 마나 증가": 167,
  "탈출의 명수": 202,
  "결투의 대가": 288,
  "질량 증가": 295,
  추진력: 296,
  "타격의 대가": 297,
  "시선 집중": 298,
  아드레날린: 299,
  속전속결: 300,
  전문의: 301,
  긴급구조: 302,
  "정밀 단도": 303,
  광기: 125,
  "오의 강화": 127,
  "강화 무기": 129,
  "화력 강화": 130,
  "광전사의 비기": 188,
  초심: 189,
  "극의: 체술": 190,
  "충격 단련": 191,
  핸드거너: 192,
  "포격 강화": 193,
  "진실된 용맹": 194,
  "절실한 구원": 195,
  점화: 293,
  환류: 294,
  "분노의 망치": 196,
  "중력 수련": 197,
  "상급 소환사": 198,
  "넘치는 교감": 199,
  "황후의 은총": 200,
  "황제의 칙령": 201,
  "전투 태세": 224,
  "고독한 기사": 225,
  세맥타통: 256,
  역천지체: 257,
  "두 번째 동료": 258,
  "죽음의 습격": 259,
  절정: 276,
  절제: 277,
  "잔재된 기운": 278,
  버스트: 279,
  "완벽한 억제": 280,
  "멈출 수 없는 충동": 281,
  심판자: 282,
  "축복의 오라": 283,
  "아르데타인의 기술": 284,
  "진화의 유산": 285,
  갈증: 286,
  "달의 소리": 287,
  피스메이커: 289,
  "사냥의 시간": 290,
  일격필살: 291,
  오의난무: 292,
  회귀: 305,
  만개: 306,
  질풍노도: 307,
  이슬비: 308,
  포식자: 309,
  처단자: 310,
  // 감소 효과
  "공격력 감소": 800,
  "공격속도 감소": 802,
  "방어력 감소": 801,
  "이동속도 감소": 803,
  // 팔찌 기본 효과
  "팔찌 기본 효과": 1,
  힘: 3,
  민첩: 4,
  지능: 5,
  체력: 6,
  // 팔찌 특수 효과
  "팔찌 특수 효과": 5,
  강타: 39,
  "긴급 수혈": 33,
  돌진: 38,
  마나회수: 36,
  "마법 방어력": 2,
  멸시: 29,
  무시: 30,
  "물리 방어력": 1,
  반격: 28,
  반전: 31,
  속공: 26,
  앵콜: 35,
  오뚝이: 37,
  "응급 처치": 34,
  "전투 중 생명력 회복량": 6,
  "최대 마나": 4,
  "최대 생명력": 3,
  타격: 40,
  투자: 27,
  회생: 32,
  // 팔지 옵션 수량
  "팔지 옵션 수량": 4,
  "고정 효과 수량": 1,
  "부여 효과 수량": 2,
};

export const engravePriority: { [key: string]: number } = {
  "에테르 포식자": 0,
  "위기 모면": 1,
  "마나 효율 증가": 2,
  "실드 관통": 3,
  "분쇄의 주먹": 4,
  "폭발물 전문가": 5,
  "탈출의 명수": 6,
  "여신의 가호": 7,
  "굳은 의지": 8,
  "마나의 흐름": 9,
  "부러진 뼈": 10,
  "강화 방패": 11,
  "약자 무시": 12,
  "번개의 분노": 13,
  "시선 집중": 14,
  불굴: 15,
  강령술: 16,
  "달인의 저력": 17,
  긴급구조: 18,
  "안정된 상태": 19,
  구슬동자: 20,
  "최대 마나 증가": 21,
  추진력: 22,
  승부사: 23,
  "강화 무기": 24,
  "광전사의 비기": 25,
  "완벽한 억제": 26,
  바리케이드: 27,
  "화력 강화": 28,
  "진실된 용맹": 29,
  심판자: 30,
  "정밀 단도": 31,
  "넘치는 교감": 32,
  "결투의 대가": 33,
  세맥타통: 34,
  "오의 강화": 35,
  "전투 태세": 36,
  광기: 37,
  "아르데타인의 기술": 38,
  "충격 단련": 39,
  "급소 타격": 40,
  "포격 강화": 41,
  초심: 42,
  "중갑 착용": 43,
  "달의 소리": 44,
  회귀: 45,
  절제: 46,
  "두 번째 동료": 47,
  "황제의 칙령": 48,
  "황후의 은총": 49,
  "중력 수련": 50,
  "슈퍼 차지": 51,
  "진화의 유산": 52,
  역천지체: 53,
  "사냥의 시간": 54,
  "죽음의 습격": 55,
  "정기 흡수": 56,
  선수필승: 57,
  환류: 58,
  갈증: 59,
  "극의: 체술": 60,
  속전속결: 61,
  일격필살: 62,
  "고독한 기사": 63,
  "잔재된 기운": 64,
  각성: 65,
  전문의: 66,
  "분노의 망치": 67,
  핸드거너: 68,
  "상급 소환사": 69,
  "질량 증가": 70,
  피스메이커: 71,
  "멈출 수 없는 충동": 72,
  "축복의 오라": 73,
  버스트: 74,
  "기습의 대가": 75,
  절정: 76,
  오의난무: 77,
  "저주받은 인형": 78,
  "절실한 구원": 79,
  이슬비: 80,
  "타격의 대가": 81,
  돌격대장: 82,
  점화: 83,
  "예리한 둔기": 84,
  처단자: 85,
  아드레날린: 86,
  포식자: 87,
  만개: 88,
  질풍노도: 89,
  원한: 90,
};

export async function apiEngravePriority() {
  let resultArray: MarketItem[] = [];
  try {
    const firstPage = await EngraveService.getMarketItems({
      Sort: "YDAY_AVG_PRICE",
      CategoryCode: 40000,
      CharacterClass: "",
      ItemTier: null,
      ItemGrade: "전설",
      ItemName: "",
      SortCondition: "ASC",
      PageNo: 1,
    });
    resultArray = [...firstPage.Items];

    const totalPages = Math.ceil(firstPage.TotalCount / 10);
    let iPage;
    for (let i = 2; i <= totalPages; i++) {
      iPage = await EngraveService.getMarketItems({
        Sort: "YDAY_AVG_PRICE",
        CategoryCode: 40000,
        CharacterClass: "",
        ItemTier: null,
        ItemGrade: "전설",
        ItemName: "",
        SortCondition: "ASC",
        PageNo: i,
      });
      resultArray = resultArray.concat(iPage.Items);
    }

    console.log(resultArray);

    const priority = resultArray.reduce((prev, cur, index) => {
      return {
        ...prev,
        [cur.Name.replace(/(\[[\u3131-\uD79D]+\]|각인서)/g, "").trim()]: index,
      };
    }, {});

    return priority;
  } catch (error) {
    console.log(error);
  }
}
